### ISSUE TITLE
GEP map issues

### ISSUE THREAD

**Issue by transitmatt** [MRT-Map/map-data#10]
cc. @iiiii7d 
Hi, for some reason the one-way arrows on Cerrito and the first block of Orinda aren't showing (and the arrows on Orinda Blvd are the wrong way). The buildings are also overlapping, could you please fix those 3 issues (faster as I don't have to create another pull request)? Thanks!

_-transitmatt_

**Comment by iiiii7d** [comment]
(hopefully) fixed in https://github.com/MRT-Map/map-data/commit/83914d4464dec20d87492ff02b82a525a4d900fe
